# Generated by Django 4.2.4 on 2023-09-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='desc2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name2',
        ),
    ]
