# Generated by Django 4.2.4 on 2023-09-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_desc_team_desc2_rename_img_team_img2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc2',
            new_name='teamdesc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img2',
            new_name='teamimg',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name2',
            new_name='teamname',
        ),
    ]
