# Generated by Django 4.2.4 on 2023-09-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_desc2_team_teamdesc_rename_img2_team_teamimg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamdesc',
            new_name='team_desc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamimg',
            new_name='team_img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamname',
            new_name='team_name',
        ),
    ]
